### PR TITLE
Real world example for CondRNN vs LSTM vs ARMAX

### PR DESCRIPTION
**Pull request by philipperemy**
Added cond_rnn, results are now as follows;
ARMA model: Mean Absolute Error (MAE) of 1.47 degrees
ARMAX model with 30 cities: MAE of 1.25 degrees
Pure autoregressive LSTM model: MAE of 1.46 degrees
Cond_rnn with 30 cities: MAE 0.87 degrees

### CODE REVIEW

**Comment by hstarmans** [comment]
Possible open issues;
* python file is created with jupytext which is mix of markdown and python
  markdown uses trailing white spaces, flake8 gives error
* Result when rendered back to notebook will probably not be perfect, indentation wise
* add package version number (there is no ```cond_rnn.__version__```)
* in setup.py ```open('README.md').read()``` will still probably fail on windows

**Comment by philipperemy** [comment]
@hstarmans thank you so much for the amazing work! Will do some edits today (if necessary) and get prepared for the merge.

**Comment by philipperemy** [comment]
Nothing to add. LGTM! Great work ;)

**Comment by hstarmans** [comment]
I was looking at the code today... column transformer needs to be specified via column numbers not column names... will prepare a fix

**Comment by philipperemy** [comment]
OKay!!

**Comment by hstarmans** [comment]
@philipperemy, I updated the code and fixed the bug with the column transformer. I added a Shapley plot to understand how the model is using the conditional vector.
I am trying to use the model to optimize a large factory and give advice to operators. The problem I have, which is also illustrated by the temperature example. Is that the model gives a good prediction but not provides me with the correct insights. It mainly looks at the temperature in Brussel and Londen to predict the temperature in Amsterdam and ignores Paris.  What I have in practice, is that operators can not influence the temperature in say Brussel but they can influence the temperature in Paris.
Ideally, I should be able to conclude that if I place a big heater in Paris. This increases the temperature in Amsterdam (and also Brussel). I will try to improve this by adding a PCA.
Simulations results are [here](https://drive.google.com/file/d/1j4lMHY0Edo8wTGwGFFHZmGbxWnKXPZmF/view?usp=sharing). The code is [here ](https://github.com/hstarmans/cond_rnn/tree/master/examples/temperature).
The Shapley values are now;
```
Brussels 1.155315
London 0.252483
Copenhagen 0.152184
Hamburg 0.093216
Frankfurt 0.089183
Geneva 0.085238
Prague 0.083077
Dublin 0.059714
Paris 0.057212
```
So from the above I would conclude that Prague or Dublin is a better place to add a heater than Paris. This conclusion is wrong, as Paris is closer.  Also a correlation matrix shows that Pearson correlation between Paris, Amsterddam and Brussels is much higher.

**Pull request merged**
